import sys, os
sys.path.insert(0, "/Applications/Blender.app/Contents/Resources/$BLENDER_VERSION/python/lib/python3.7/site-packages")
sys.path.insert(0, "/Users/robstenson/Goodhertz/coldtype")

from coldtype.blender import *
import pickle

BPH.Clear()
tc = BPH.Collection("Autogenerated")
